# This is a basic workflow that is manually triggered
# Is it a ci?

name: Compile or Release

on:
  pull_request:
    paths: ["source/**", "include/**"]
    branches: [main]

  push:
    paths: ["source/**", "include/**", "pushtrigger.txt"]
    branches: [main]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build with sm-${{ matrix.sm_version }}

    strategy:
      fail-fast: false
      matrix:
        sm_version: ["1.12", "1.13.7295"]

    runs-on: ubuntu-latest
    outputs:
      pushtrigger: ${{ steps.filter.outputs.pushtrigger }}

    steps:
      - uses: actions/checkout@v6
        name: Checkout Repo
        with:
          submodules: recursive

      - name: Retrive Date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - uses: actions/setup-python@v6
        name: Prepare Python
        with:
          python-version: 3.11

      - name: Set up NinjaBuild
        run: sudo apt-get update && sudo apt-get install -y ninja-build

      - uses: rumblefrog/setup-sp@master
        name: Install SourcePawn Compiler
        with:
          version: ${{ matrix.sm_version }}

      - name: Configure and Build
        run: |
          python3 configure.py --spcomp-dir "$scriptingPath"
          ninja

      - uses: actions/upload-artifact@v7
        name: Upload the Package
        with:
          name: modified-plugins-sm-${{ matrix.sm_version }}-${{ env.DATE }}
          path: |
            build/source/
            build/include/
            LICENSE
            README.md
            README-cn.md

      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            pushtrigger:
              - 'pushtrigger.txt'

  release:
    strategy:
      fail-fast: false
      matrix:
        sm_version: ["1.12", "1.13.7295"]

    name: Release with sm-${{ matrix.sm_version }}
    if: ${{ needs.build.outputs.pushtrigger == 'true' }}
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        name: Checkout Repo

      - name: Prepare Env
        run: | 
             echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
             echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Download package
        uses: actions/download-artifact@v4
        with:
          path: tmp/
          pattern: modified-plugins-sm-${{ matrix.sm_version }}-${{ env.DATE }}
          merge-multiple: false

      - name: Prepare Release
        working-directory: tmp/
        run: |
          for i in */; 
          do 
            zip -0 -r "${i%/}.zip" "$i" & 
          done; 
          wait

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v3
        with:
          tag_name: release-${{ env.DATE }}
          name: modified-plugins-${{ env.DATE }}
          body_path: release_body.md
          files: tmp/modified-plugins-sm-${{ matrix.sm_version }}-*.zip
          make_latest: true
          overwrite_files: true
